[project]
name = "chainlit-llama-index-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit==2.5.5",
    "db-dtypes>=1.4.2",
    "fastembed>=0.4.2",
    "google-cloud-bigquery>=3.30.0",
    "google-cloud-bigquery-storage>=2.30.0",
    "llama-index>=0.12.30",
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "qdrant-client>=1.12.1",
    "sqlparse>=0.5.3",
    "unidecode>=1.4.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "ruff>=0.11.5",
]
