[project]
enable_telemetry = false
user_env = []
session_timeout = 3600
user_session_timeout = 1296000  # 15 days
cache = true
allow_origins = ["*"]

[features]
unsafe_allow_html = true
latex = false
user_message_autoscroll = true
auto_tag_thread = false
edit_message = false

[features.spontaneous_file_upload]
    enabled = false
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    sample_rate = 24000

[UI]
name = "Food Advisor"

default_theme = "light"

# layout = "wide"
# description = ""

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "tool_call"

custom_css = '/public/stylesheet.css'
# custom_js = "/public/script.js"

login_page_image = "/public/login_background.jpeg"

[[UI.header_links]]
    name = "Source Code"
    display_name = "GitHub"
    icon_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/2048px-Octicons-mark-github.svg.png"
    url = "https://github.com/insight-engineers/tripadvisor-foodbot"

[meta]
generated_by = "2.4.201"