# .github/workflows/linter.yaml

name: Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python:
    name: Lint Python Code
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.13"

      - name: Install dependencies
        run: uv sync

      - name: Run linters
        run: uv run ruff check .
