# .github/workflows/test.yaml

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.13"

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest -v -W ignore::DeprecationWarning --junit-xml=test-results.xml
        env:
          STREAMLIT_FILE_PATH: _streamlit.py

      - name: Output Test Results
        if: always()
        uses: pmeier/pytest-results-action@v0.7.1
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          title: Pytest Results
